[package]
name = "dioxus-bug"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { git = "https://github.com/DioxusLabs/dioxus"}
dioxus-tui = { git = "https://github.com/DioxusLabs/dioxus"}